### ISSUE TITLE
Cannot connect to robot

### ISSUE THREAD

**Issue by Bo887** [FRCDashboard/FRCDashboard#23]
Upon attempting to connect to the robot (using the IP address of the roboRIO), I get this message:
![dashboarderror](https://user-images.githubusercontent.com/16738329/27354223-b6cd261a-55bb-11e7-86fa-230f3673154b.PNG)

I am using the default code provided with no modifications.

**Comment by ErikBoesen** [comment]
@rakusan2 Any ideas? Looks like this is from your code.

**Comment by rakusan2** [comment]
what version of wpilib-nt-client do you have?

**Comment by Bo887** [comment]
1.2.6

**Comment by AdamBusch** [comment]
I have this same issue as well, happening from a new project as well.

**Comment by ErikBoesen** [comment]
@rakusan2 Any ideas?

**Comment by rakusan2** [comment]
version 1.x is not able to deal with packets that have been split
version 2.x will while also giving a more detailed error report

**Comment by rakusan2** [comment]
I should be finished with version 2 in two week since it will require an almost complete rewrite

**Comment by rakusan2** [comment]
Sorry for the long delay but work kept getting in the way till I had forgotten.
On the other hand I had decided to hold out on 2.0 till I have more time and just make a quick fix on 1.x and release **1.3.0**
Based on the tests that I had done, this one is able to handle split packets.
I would appreciate a confirmation on that with your own code since I only have a hath running simulator on hand
