### ISSUE TITLE
Should not correct for booleans being strings in every single listener

### ISSUE THREAD

**Issue by ErikBoesen** [FRCDashboard/FRCDashboard#27]

**Comment by ErikBoesen** [comment]
@rakusan2 Does your Node server account for this?

**Comment by rakusan2** [comment]
My wpi-nt-client package does not modify any types, tho it will give you an error if the type that the NT server has is different than what you are supplying

**Comment by ErikBoesen** [comment]
I'd recommend that you add automatic conversion from string to boolean if valid.

**Comment by rakusan2** [comment]
I am worried about false positives on stuff coming from the NT server since there might be users expecting boolean values in string form. Therefore I can make it as an optional feature, but I think it is better to leave this conversion up to the users on their side. 
For example you can make this function easily in main.js

**Comment by ErikBoesen** [comment]
It's a gigantic pain to have to account for `true` being a string in every listener, though.

**Comment by ErikBoesen** [comment]
Okay, this should be good now, other than one thing.

Someone still needs to remove the checks from all the listeners in `ui.js` since they shouldn't be necessary anymore. I would do it myself, but I'd rather someone else get the experience. @ianzullo, want to take a swing at this? Shouldn't be too hard.
