### ISSUE TITLE
Usage with USB webcam

### ISSUE THREAD

**Issue by calebeby** [FRCDashboard/FRCDashboard#3]
Hello,
I'm from team 1432 and we're looking into using your dashboard. So far it looks great, except I can't figure out how to use this with a USB webcam. I realize that I have to change `style.css` and the background image url, but I do not know what to change this to.

Thanks, Caleb

**Comment by ErikBoesen** [comment]
Glad to hear you're interested in using my application!

This is one of the challenges I'm going through in making the dashboard more easy to mess with.

Since there's a variety of ways to hook up a camera, I'm not sure exactly what to tell you. **However**, I can tell you how our team does it. I think that should get you on the right track.

We use the MPEG Streamer library (I think [this one](https://github.com/jacksonliam/mjpg-streamer)). If you open the configuration page up while connected to your robot, there's a selection of ways to view your camera output. Find whichever one provides raw images. Get the src of the image. Put that into the stylesheet in the obvious place. It should work.

I realize what a terrible explanation that is, and I'm sorry, I just don't know that much about how the camera streamer system works yet. If it helps, I'm currently redeveloping this year's version of our team's UI, off which FRCDB is based, with the extremely simplified FRC Dashboard library. You can find it, and see how I did the camera for it, [here](https://github.com/frc1418/FRCDashboard).

If you already have a different type of dashboard with a streaming system, you can take a look at that and see how it works or where it's getting its source from.

If you want to give me a link to that, feel free to do so and I'll see if I can help.

If you need more help (with this or anything else), feel free to ask.

Best of luck and thanks again for using FRC Dashboard!

**Comment by calebeby** [comment]
Last year we were using the java smartdashboard, but I have no idea how that works

**Comment by ErikBoesen** [comment]
Does that have camera support? I'm pretty sure it doesn't, but there may be something I don't know.

**Comment by calebeby** [comment]
Yeah, the camera stream is there.

**Comment by calebeby** [comment]
I installed mpeg-streamer via https://github.com/robotpy/roborio-packages

**Comment by calebeby** [comment]
Then I rebooted the roborio, and went to http://roborio-1432-frc.local:5800/ , but it didn't load

**Comment by ErikBoesen** [comment]
Oh, yeah, sorry, that's the one I was looking for.

That IP might not be a global thing. I think it's something just our team uses.

**Comment by ErikBoesen** [comment]
https://www.chiefdelphi.com/forums/showthread.php?t=101314

I'm looking at this.

Do you know how you can get the IP of your camera? Maybe ask your mechanics team. They should know.

**Comment by calebeby** [comment]
https://www.chiefdelphi.com/forums/showthread.php?t=101314

they talk about configuring the camera with the tool that frc provided. Any idea what that tool is?

**Comment by ErikBoesen** [comment]
Sorry, I forgot to push my code. Should be there now.

**Comment by calebeby** [comment]
You are using a usb webcam, right?

**Comment by ErikBoesen** [comment]
Hmm, I don't know what utility they're speaking of. Let me ask some of the others on my team.

And yes, we are.

**Comment by calebeby** [comment]
10.14.32.2?action=stream does not load either. When I go back to robotics on Monday, I will check and see if I can find another ip for the robot. Thanks

**Comment by calebeby** [comment]
whoops didn't mean to close this.

**Comment by ErikBoesen** [comment]
That's just the IP of our camera. Probably not yours. Ask around your team and see if anyone knows the camera IP or how to get it.

Sorry I haven't been so helpful, please tell me if you have any ideas to improve the explanation in the `README` et al.

Also, if you ever need to manage input from multiple camera streams, I'm about to update the [MultiCamera addon](https://github.com/FRCDashboard/addon-MultiCamera). It's currently broken but should be fixed by tomorrow.

**Comment by ErikBoesen** [comment]
Did you learn anything from the rest of your team?

**Comment by calebeby** [comment]
No. I'm the only programmer, except for our programming mentor, who I might
get to talk to on Friday. I emailed @virtuald regarding this, and he gave
me a few suggestions. I emailed him back, but he hasn't responded yet.

Thanks for your help!

I will get back to this thread once I get a response from Dustin.

**Comment by ErikBoesen** [comment]
Excellent, glad to hear you're getting somewhere with this issue.

**Comment by calebeby** [comment]
OK. I figured this out with @virtuald. It turns out that `roborio-packages` was missing `libv4l` when it installed, but we got it worked out. Thanks!

**Comment by ErikBoesen** [comment]
Excellent, glad to hear. Feel free to open another help wanted issue if you have any other questions.
