### ISSUE TITLE
Image stream is background-image

### ISSUE THREAD

**Issue by calebeby** [FRCDashboard/FRCDashboard#6]
Don't you think that the image stream should be a `<img src=""/>` instead of `background-image`? That way the content is in the `HTML` and the styles are in the `CSS`.

**Comment by ErikBoesen** [comment]
It used to be this way. I believe we changed it so that it was easier to manipulate the image (`background-size: cover` could be used, for example). So I think we'll keep it that way for now. Although you are right that it makes more sense to have the content in the HTML. You're welcome to change it for yourself (and even pull req) if you like.

Oh, and just a side note, you don't need to include the `/` at the end of the `img` tag. That was deprecated in the HTML5 spec. So, just `<img src="path/to/img.png">` is fine, as are `<br>`, `<hr>`, etc.
